### ISSUE TITLE
Wrong formula is used in expose function

### ISSUE THREAD

**Issue by Jinsung-L** [scttcper/ts-trueskill#203]
In `TrueSkill.expose()` method:
https://github.com/scttcper/ts-trueskill/blob/9bca90ec27a116579d2eee89329808f6326f3bfe/src/trueskill.ts#L263

Whereas this should be:
https://github.com/sublee/trueskill/blob/91c29b1ab6cd86d6d68fc983fd7ceba3a88ad544/trueskill/__init__.py#L580

Ref. https://www.microsoft.com/en-us/research/project/trueskill-ranking-system/

> Using the two parameters μ and σ which characterize a belief in a player’s skill the TrueSkill ranking system ranks players using the so-called conservative skill estimate = μ – k*σ.

**Comment by scttcper** [comment]
Thanks for checking it!
