### ISSUE TITLE
Performance difference when compiled for ES5 instead of ES6

### ISSUE THREAD

**Issue by wraithan** [scttcper/ts-trueskill#7]
Howdy,

I was checking out your library to see about using it. Obviously with anything math intense like this the performance in JS is limited, but I need to maximize throughput. One of the immediate red flags was that your `tsconfig.json` is targetting ES6 instead of ES5. Unfortunately not all ES6 features have been optimized yet, especially if you aren't on a bleeding edge JS engine. Using Node 6.10.2, I was able to gain about 10% more calls per second to the `trueskill.quality` function just by changing a couple of lines to make them compile in ES5 mode then making a new build.

Only thing I couldn't find a convenient backfill for was the `Function.name` that is being used for debug logging because TypeScript knows that might not be there. My fork/branch also has some tweaks so I could publish a scoped package to make using my fork easier in our deployment process. I am happy to split the changes and find a way to fix the debug logging if you are interested in changing the compile target to ES5.

If not, I'm happy to just maintain my floating patches on top of your library. It is an incredibly convenient library for us, so I'll likely spend more time attempting to optimize it or the underlying libraries as I think I can eek more performance out of it. If my fork is going to live much longer on npm then I'll make sure to update the metadata and README to make it clear it is a fork for a very minor reason.

If you'd like to check out my fork it is here: https://github.com/wraithan/ts-trueskill/tree/wraithan/es5
If you'd like to try my forked version and test the performance difference you can install it from npm here: https://www.npmjs.com/package/@wraithan/ts-trueskill

Thanks for making this amazing clone of the python trueskill library

**Comment by scttcper** [comment]
Thanks for taking the time to read and use the code. Make a PR with those changes, switching to es5 sounds good to me. I'm not sure why i went with es6, I think I liked that the code stayed closer to the typescript original, but it doesn't matter.

**Comment by scttcper** [comment]
Got excited and merged it. Shoot over whatever changes you come up with. Only feedback on the last one was to prefer lodash's _.fill solution over writing another loop. Released 1.1.0 in es5

**Comment by wraithan** [comment]
Nice! I'll switch our builds to use that instead of my fork.

I should really learn what's in lodash one day, I'm just so used to writing vanilla JS. I'll refresh myself on the lodash API next time before diving into this.

Thanks for the invite to collaborate too! I'll certainly try to take you up on that, currently the performance bottlenecks that I found were deeper in the underlying libraries that handle the matrix math. Lots of small objects created and destroyed thrashing memory a bit and making the GC sad.

**Comment by scttcper** [comment]
How were you benchmarking? Might be useful to have something in the repo.

**Comment by wraithan** [comment]
Mostly via a custom script and verifying via the webkit profiler. I was
thinking of building a better testing jig for making sure trueskill
libraries give reasonably same results.

Most of my performance test focused on 1v1 and 3v3. I used ratings that I
sampled from real data to generate groups for matches. For the 3v3 a lot of
the test was taking a group of 6 and finding the best balanced team by
getting the draw chance for each possible configuration.

My benchmarking stuff was in JS, not TS, since we use JS at work. I'll see
about making a nicer TS version.
